title: Ent-Lab Group
logo: /assets/img/new-logo.png
description: Embedded and Networked Things Group, University of Trento, Italy
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

sidebar:
  - name: About
    icon: <span class="material-symbols-outlined"> settings_accessibility </span>
    link: /about.html
  - name: Members
    icon: <span class="material-symbols-outlined"> groups </span>
    link: /members.html
  - name: Open Source Projects
    icon: <span class="material-symbols-outlined"> apps </span>
    link: /open-source.html   
  - name: Publications
    icon: <span class="material-symbols-outlined"> star_half </span>
    link: https://scholar.google.com.tr/citations?hl=en&user=LXUvnL0AAAAJ&view_op=list_works&sortby=pubdate
  - name: GitHub
    icon: <span class="material-symbols-outlined"> activity_zone </span>
    link: https://github.com/tinysystems    
  - name: Contact
    icon: <span class="material-symbols-outlined"> contact_phone </span>
    link: /contact.html

publications:
  - name: "AdaMICA: Adaptive Multicore Intermittent Computing"
    link: 
    venue: "Proc. ACM Interact. Mob. Wearable Ubiquitous Technol. Volume 6, Issue 4, September 2022 and ACM UbiComp 2022"    
  - name: "Immortal Threads: Multithreaded Event-driven Intermittent Computing on Ultra-Low-Power Microcontrollers"
    link: https://www.usenix.org/conference/osdi22/presentation/yildiz
    venue: "16th USENIX Symposium on Operating Systems Design and Implementation (OSDI 22)"
